# Generated by Django 5.2.10 on 2026-04-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='villa',
            name='image_url',
        ),
        migrations.AddField(
            model_name='villa',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='villas/'),
        ),
    ]
