# Generated by Django 6.0.3 on 2026-03-16 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('villas', '0003_alter_amenity_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={'verbose_name_plural': 'Amenities'},
        ),
    ]
